# basic config
host:
  port: 8085
  name: localhost
  protocol: http

database:
  type: postgres
  host: db
  port: 5432
  username: postgres
  password: fm210680
  database: cookbookdb
  synchronize: true
  logging: false

# Remove this, sample extra config
# Pagination 

pagination:
  rowsSkip: 5;
  rowsNumber: 5;

sample:
  title: A full node backend